version: "3.7"
services:
  safeway-coupons:
    image: ghcr.io/smkent/safeway-coupons:latest
    environment:
      CRON_SCHEDULE: "0 2 * * *" # Set your desired cron schedule
      SMTPHOST: your.smtp.host
      SAFEWAY_ACCOUNT_USERNAME: chase200456@yahoo.com
      SAFEWAY_ACCOUNT_PASSWORD:
      SAFEWAY_ACCOUNT_MAIL_FROM: chase200456@yahoo.com
      SAFEWAY_ACCOUNT_MAIL_TO: chase200456@yahoo.com
    restart: unless-stopped
    
#IMPORT INFO, HOW TO RUN THIS FILE + API
#INSTALL DOCKER ONTO COMPUTER/VSCODE
#git clone https://github.com/smkent/safeway-coupons.git
#cd <repository-folder>
#Start the Docker Container - docker-compose up -d
#Check Logs for Debugging - docker-compose logs -f
# Install Python Package (Optional) - pip install safeway-coupons
